### PR TITLE
Suppress TTY forwarding and interactive when stdin is not a TTY

### PR DESCRIPTION
**Pull request by rwalker-apple**
#### Problem
 restyle-path can't be used with xargs or other invocation schemes that hand the script a pipe or other device for stdin

 #### Proposed Changes
 1. use bash (for array variables)
 2. only forward the TTY and run interactively if stdin is a TTY

### CODE REVIEW

**Comment by rwalker-apple** [comment]
I found a few other places where docker is run with `-it` that don't look like they should be interactive...

**Review by pbrisbin — CHANGES_REQUESTED** [review]
Thanks for catching this!

Ideally, we'd be able to keep this script POSIX. It'd not a super hard requirement, but I think in this case it wouldn't be too difficult to avoid the arrays. The approach I usually use is a function:

```sh
docker_run() {
  if [ -t 0 ]; then
    exec docker run -it "$@"
  else
    exec docker run "$@"
}

docker_run \
  # all as before
```

I'm also a little fuzzy on the best conditions to choose `--interactive` or `--tty`. Is checking only stdin in ideal? Or do we need to look at stdout too? Should one condition drive both flags or are they different?

As for the `Makefile` I do want `-it` there (I think). Just because `make` is executing the command doesn't mean it's any less interactive. I want `^C` to work and colors to appear in the output, which `-it` gives you. Do let me know if I'm missing something there.

**Comment by rwalker-apple** [comment]
I think [ -t 0 ] is sufficient.  We're just trying to keep `docker run` from failing, which apparently only occurs when stdin isn't a TTY and when -t is passed.

As far as control-C, my testing indicates that docker run doesn't respond to control-C whether I use -it  or not, and invoking from a makefile doesn't change this.  I'm on MacOS, so YMMV.

**Comment by pbrisbin** [comment]
Thanks for this! Merged, and built-upon a bit.

> my testing indicates that docker run doesn't respond to control-C

Ugh. I find this a lot and never get to the bottom of it. Oh well.

**Comment by rwalker-apple** [comment]
wow, lots of add-ons.  nice.

**Pull request merged**
