### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DanielHabenicht**
add documentation link

### CODE REVIEW

**Comment by pbrisbin** [comment]
Thanks for this! I might move it around a little, maybe mention the Haddocks too. I'll merged a version if this tomorrow.

**Comment by pbrisbin** [comment]
I'm actually going to close this for something a bit more holistic.

I'll add a `CONTRIBUTING` link to all three repositories (restyled.io, restyler, restylers), which links to this page: https://github.com/restyled-io/restyled.io/wiki/Contributing-to-Restyled, and then maintain that page as the single reference point out to anything generally useful in this space. It's subjective, but having this link in this README felt off on two axis: it's too specific a README, and it links out to too in-specific a place.

Thanks for the nudge though, you're right that some pointer here makes sense.

**Comment by DanielHabenicht** [comment]
Yeah it's just that all three repos documentation are in the wiki and if someone is looking for "How does that work?" he/she doesn't have a quick way to find it. 

I didn't want to see the contribution guide. (Personally)

**Comment by pbrisbin** [comment]
Yeah, that's fair. This decision came out of a few (again, subjective) beliefs:

1. 80% of people seeking this information are hitting the wiki first, not the other way around. Linking repo -> wiki felt circular. And doing it in only this repository felt insufficient anyway.

1.  "How does [the `restyled.io|restyler|restylers` repository] work?" should be answered by content right in the appropriate `README`, which we should do.

1. "How does Restyled work [for the purposes of me interacting with this source repository]?" is close enough to "contributing", that the _Contributing_ page is the best footer link to answer with. If you find that's not the case, we should expand that page

**Pull request closed without merging**
